-- Áß­ Äõ¸® - °ýÈ£¾ÈÀ» ¸ÕÀú ½ÇÇàÇÔ, FROMÀý - ÀÎ¶óÀÎºä
SELECT ROWNUM, NAME, SCORE FROM
(SELECT ROWNUM, NAME, SCORE
FROM EX_SCORE
ORDER BY score DESC)
WHERE ROWNUM <= 5;

-- JOB_INFO Å×ÀÌºí
CREATE TABLE JOB_INFO(
    JOB_ID VARCHAR(10),
    MIN_SALARY NUMBER,
    MAX_SALARY NUMBER
);
DROP TABLE JOB_INFO;

INSERT INTO JOB_INFO VALUES ('AD_PRES', 20080, 40000);
INSERT INTO JOB_INFO VALUES ('AD_VF', 15000, 30000);
INSERT INTO JOB_INFO VALUES ('AD_ASST', 3000, 6000);
INSERT INTO JOB_INFO VALUES ('FI_MGR', 8200, 16000);
INSERT INTO JOB_INFO VALUES ('FI_ACCOUNT', 4200, 9000);
INSERT INTO JOB_INFO VALUES ('AD_MGR', 8200, 16000);
INSERT INTO JOB_INFO VALUES ('AD_ACCOUNT', 4200, 9000);

SELECT * FROM JOB_INFO;
--Áý°è ÇÔ¼ö - COUNT(), SUM(), AVG()
SELECT COUNT(*) ÃÑ°³¼ö,
       ROUND(AVG(MIN_SALARY), -1) ÃÖÀú±Þ¿©Æò±Õ,
       AVG(MAX_SALARY) ÃÖ´ë±Þ¿©Æò±Õ
FROM JOB_INFO;

-- ÃÖÀú ±Þ¿©°¡ 5000 ´Þ·¯ ÀÌ»óÀÎ Á÷¾÷ÀÌ¸§À» °Ë»öÇÏ½Ã¿À
SELECT JOB_ID Á÷¾÷ÀÌ¸§, MIN_SALARY "min_sal"
FROM JOB_INFO
WHERE MIN_SALARY > 5000;
--WHERE min_sal > 5000; -> ¼ø¼­·Î ÀÎÇØ WHERE Àý¿¡¼­ min_salÀ» ÀÎ½Ä¸øÇÔ

-- ÃÖÀú ±Þ¿©°¡ 5000 ´Þ·¯ ÀÌ»óÀÎ Á÷¾÷ ¾ÆÀÌµð¸¦ °Ë»öÇÑ ºä¸¦ ÀÛ¼ºÇÏ½Ã¿À
-- CREATE VIEW ºäÀÌ¸§ AS ±¸¹®
CREATE VIEW V_JOB_INFO AS
SELECT *
FROM JOB_INFO
WHERE MIN_SALARY > 5000;


SELECT * FROM V_JOB_INFO;

-- ÃÖ°í±Þ¿©¿Í ÃÖÀú±Þ¿©ÀÇ Â÷°¡ 8000 ÀÌ»óÀÎ Á÷¾÷¾ÆÀÌµðÀÇ ¼ö¸¦ °Ë»öÇÏ½Ã¿À
SELECT COUNT(*)
FROM JOB_INFO
WHERE MAX_SALARY - MIN_SALARY > 8000;

-- ÃÖ°í±Þ¿©¿Í ÃÖÀú±Þ¿©ÀÇ Â÷°¡ 8000 ÀÌ»óÀÎ Á÷¾÷¾ÆÀÌµð¸¦ °Ë»öÇÏ½Ã¿À
SELECT JOB_ID
FROM JOB_INFO
WHERE MAX_SALARY - MIN_SALARY > 8000;

-- Á÷¾÷ ¾ÆÀÌµðÀÇ ÀÌ¸§ÀÌ AD·Î ½ÃÀÛÇÏ´Â ÀÚ·á¸¦ °Ë»öÇÏ½Ã¿À
SELECT *
FROM JOB_INFO
WHERE JOB_ID LIKE 'AD%';


-- ºä »èÁ¦
-- DROP VIEW V_JOB_INFO;
